- hosts: all
  become: true
  tasks:
    - name: install misc programs

      script: /home/ubuntu/CNE-project2/scripts/misc_install.sh

    - name: install docker from script
      script: /home/ubuntu/CNE-project2/scripts/docker-install.sh

    - name: install docker_compose from script
      script: /home/ubuntu/CNE-project2/scripts/docker_compose.sh

- hosts: jenkins_VM
  become: true
  tasks:
    - name: install jenkins from script

      script: /home/ubuntu/CNE-project2/scripts/install-jenkins.sh

    - name: install Kubernetes from script
      script: /home/ubuntu/CNE-project2/scripts/kubernetes_install.sh

    - name: install aws_cli from script
      script: /home/ubuntu/CNE-project2/scripts/aws_cli.sh
